runtime: go121
env: standard

instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  DB_URI: "mongodb://localhost:27017"
  DB_NAME: "divadb"
  DB_COLLECTION_NAME: "todolist"
