runtime: go121
env: standard

instance_class: F1

handlers:
  - url: /.*
    script: auto
    secure: always

env_variables:
  DB_URI: "mongodb+srv://divadb:divadbuser@divadb.kzthfni.mongodb.net/?appName=divadb"
  DB_NAME: "divadb"
  DB_COLLECTION_NAME: "todolist"
